#name of the task
name: 'Add Project Lead as Reviewer for PR'
#Starting the action on any activity in PR
on: 
  pull_request:
    [opened]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml"
