
name: Greetings

on:
  pull_request:
    types: [closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
    - uses: Manoj-Paramsetti/Greeting-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_message: 'Thank you for taking out your time and contributing to our project.<br>This pull request is closed by ${{github.actor}}'
